// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.github.kaakaa.mattermost-plugin-reacji",
  "name": "Reacji Channeler",
  "description": "Move post to other channel by attaching reactions",
  "version": "0.1.0",
  "min_server_version": "5.30.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "AllowDuplicateSharing",
        "display_name": "Allow duplicate sharing",
        "type": "bool",
        "help_text": "",
        "placeholder": "",
        "default": false
      },
      {
        "key": "DaysToKeepSharedRecord",
        "display_name": "Days to keep shared record",
        "type": "number",
        "help_text": "",
        "placeholder": "",
        "default": 30
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
