// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	store "github.com/kaakaa/mattermost-plugin-reacji/server/store"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Reacji provides a mock function with given fields:
func (_m *Store) Reacji() store.ReacjiStore {
	ret := _m.Called()

	var r0 store.ReacjiStore
	if rf, ok := ret.Get(0).(func() store.ReacjiStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.ReacjiStore)
		}
	}

	return r0
}

// Shared provides a mock function with given fields:
func (_m *Store) Shared() store.SharedStore {
	ret := _m.Called()

	var r0 store.SharedStore
	if rf, ok := ret.Get(0).(func() store.SharedStore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.SharedStore)
		}
	}

	return r0
}
